### ISSUE TITLE
Global CSS is being imported by blitzDataProvider

### ISSUE THREAD

**Issue by kmdavis** [theapexlab/ra-data-blitz#11]
```
error - ./app/core/styles/index.scss
Global CSS cannot be imported from files other than your Custom <App>. Due to the Global nature of stylesheets, and to avoid conflicts, Please move all first-party global CSS imports to app/pages/_app.tsx. Or convert the import to Component-Level CSS (CSS Modules).
Read more: https://nextjs.org/docs/messages/css-global
```

My app has a global stylesheet at `app/core/styles/index.scss`, which is ONLY imported by `app/pages/_app.tsx`. After a lot of bisecting, I've determined that not instantiating this data provider fixes the issue, but of course, breaks everything else. I was able to implement a resource specific version of the getList portion of the data provider, using a dynamic import and the invoke method, and that works, so I'm not sure what could be causing this.

```tsx
const ReactAdmin = () => {
  return (
    <Admin
      // using blitzDataProvider breaks with the following error:
      //
      // error - ./app/core/styles/index.scss
      // Global CSS cannot be imported from files other than your Custom <App>. Due to the Global nature of stylesheets, and to avoid conflicts, Please move all first-party global CSS imports to app/pages/_app.tsx. Or convert the import to Component-Level CSS (CSS Modules).
      // Read more: https://nextjs.org/docs/messages/css-global
      //
      // dataProvider={blitzDataProvider({ invoke, searchEntities })}
      dataProvider={{
        async getList(resource, params) {
          if (resource === "users") {
            const { default: getUsers } = await import("app/users/queries/getUsers")
            const users = await invoke(getUsers, {})
            return {
              data: users.users,
              total: users.count,
            }
          }
          return {
            data: [],
            total: 0,
          }
        },
      }}
    >
      // User views copy pasted from the example repo
      <Resource name="users" list={UserList} edit={UserEdit} create={UserCreate} />
    </Admin>
  )
}
```

**Comment by kmdavis** [comment]
I dug in a bit more, and the issue occurs when the getHandler is imported, specifically, it complains about https://github.com/theapexlab/ra-data-blitz/blob/main/src/utils/getHandler.ts#L9-L13

There is a deprecation notice that is emitted a couple seconds before the fatal error occurs:
```
(node:72800) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
```
and this deprecation warning (and the error) go away if this one line is commented out.

**Comment by kmdavis** [comment]
narrowed it down slightly further, as far as I can take it. issue is with the `__importStar` in the output

**Comment by kmdavis** [comment]
Implemented my own version of this data provider, including generic imports, and got the same error. I was able to fix it using webpack magic comments, such as `/* webpackInclude: /app\/\w+\/mutations\/create\w+\.ts/ */`

**Comment by m4tty-d** [comment]
Sorry for the late reply.
If you managed to find a generic solution, just submit a PR and I'm happy to merge it in.
@kmdavis
