### ISSUE TITLE
getOne doesn't expect UUIDs

### ISSUE THREAD

**Issue by makivlach** [theapexlab/ra-data-blitz#12]
I've discovered that this package only expects IDs to be integers. I've made a pull request which extends 'getOne' to expect either integer or string

**Comment by makivlach** [comment]
@m4tty-d Could you take a look at the pull request pls?

**Comment by m4tty-d** [comment]
@makivlach sorry just seeing this. I merged your PR, thank you for the contribution 🙌 :))
