### ISSUE TITLE
Adding an API route causes the build to fail.

### ISSUE THREAD

**Issue by chimame** [theapexlab/ra-data-blitz#3]
## Overview
If you add an API route, it will be built for the client.

## Problem
Blitz allows you to [add a third party login](https://blitzjs.com/docs/passportjs). When you do this, you will need to add an API root. Normally, API routes are built for the server, so there is no problem, but when using ra-data-blitz, they cannot be built. The cause of this is the process of identifying the handler in the blitzDataProvider provided by ra-data-blitz. The blitzDataProvider, which is provided by ra-data-blitz, is designed to import all handlers, especially those under `app/`. So using react-admin and the blitzDataProvider under `app/pages/` will cause the `app/api/` to be built for the client as well.

https://github.com/theapexlab/ra-data-blitz/blob/4c2bbd5d951d043331f51ab5c5f82f4520c6d14b/src/utils/getHandler.ts#L9

## countermeasure
How about narrowing down the handlers to be read by using `app/react-admin` or `app/${resource}/react-admin/${folder}/` instead of `app/`?

**Comment by m4tty-d** [comment]
Thanks for the suggestion @chimame!

We can add a `handlerRoot` option to `BlitzDataProviderParams`, with a default value `app/`.

What do you think? Would this solve your problem?

**Comment by chimame** [comment]
@m4tty-d thanks!

I think it's a great suggestion.
It would solve this problem!

**Comment by m4tty-d** [comment]
Thanks for your contribution @chimame. 🙌
It's released under v0.0.10 #7.

**Comment by chimame** [comment]
@m4tty-d Thanks for the merge.
I will use the released version immediately.
